[package]
name = "hello_remote_world"
version = "0.1.0"
authors = ["VS Code <vscode@microsoft.com>"]

[lib]
path ="./src/lib/lib.rs"

[dependencies]
day01.path = "day01"
day02.path = "day02"
day03.path = "day03"
day04.path = "day04"
